using System;
using System.Linq;
using System.Windows;
using Microsoft.EntityFrameworkCore;
using RGBSelcer.Data;
using RGBSelcer.Models;

namespace RGBSelcer
{
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            using var context = new AppDbContext();
            context.Database.EnsureCreated();

            if (!context.Users.Any(u => u.Login == "GURSKIY"))
            {
                context.Users.Add(new User
                {
                    Login = "GURSKIY",
                    PasswordHash = BCrypt.Net.BCrypt.HashPassword("IGOR"),
                    CreatedAt = DateTime.Now
                });
                context.SaveChanges();
            }

            if (!context.Cars.Any())
            {
                SeedCars(context);
            }
        }

        private static void SeedCars(AppDbContext context)
        {
            var cars = new Car[]
            {
                // ===== BMW =====
                new Car { Brand = "BMW", Model = "M3 Competition", Year = 2024, Price = 8_900_000m, LicenseCategory = "B", MaxSpeedKmh = 290, HorsePower = 510, EngineType = "Бензиновый R6 Twin-Turbo", EngineVolume = 3.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 10.2, Seats = 5, BodyType = "Седан", DriveType = "Задний", Color = "Синий", Acceleration0to100 = 3.9, Weight = 1730, Country = "Германия", Description = "BMW M3 Competition — эталонный спортивный седан с 510-сильным рядным шестицилиндровым двигателем, задним приводом и идеальным балансом. Легенда автоспорта на каждый день." },
                new Car { Brand = "BMW", Model = "X5 xDrive40i", Year = 2024, Price = 9_500_000m, LicenseCategory = "B", MaxSpeedKmh = 243, HorsePower = 381, EngineType = "Бензиновый R6 Turbo", EngineVolume = 3.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-95", FuelConsumption = 9.8, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Чёрный", Acceleration0to100 = 5.4, Weight = 2185, Country = "Германия", Description = "BMW X5 — премиальный внедорожник с динамичным характером. Просторный салон, передовые технологии и уверенность на любой дороге." },
                new Car { Brand = "BMW", Model = "7 Series 740i", Year = 2024, Price = 12_500_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 380, EngineType = "Бензиновый R6 Turbo", EngineVolume = 3.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 8.5, Seats = 5, BodyType = "Седан", DriveType = "Задний", Color = "Серебристый", Acceleration0to100 = 5.0, Weight = 2060, Country = "Германия", Description = "BMW 7 Series — флагманский седан класса люкс с театральным экраном, массажными креслами и передовыми системами помощи водителю." },
                new Car { Brand = "BMW", Model = "i4 M50", Year = 2024, Price = 7_800_000m, LicenseCategory = "B", MaxSpeedKmh = 225, HorsePower = 544, EngineType = "Электрический", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Купе", DriveType = "Полный", Color = "Белый", Acceleration0to100 = 3.9, Weight = 2215, Country = "Германия", Description = "BMW i4 M50 — полностью электрический Gran Coupe с мощностью 544 л.с. Запас хода до 510 км, M-шасси и нулевые выбросы." },
                new Car { Brand = "BMW", Model = "S 1000 RR", Year = 2024, Price = 2_400_000m, LicenseCategory = "A", MaxSpeedKmh = 299, HorsePower = 210, EngineType = "Бензиновый R4", EngineVolume = 1.0, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-98", FuelConsumption = 6.4, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 3.1, Weight = 197, Country = "Германия", Description = "BMW S 1000 RR — суперспортивный мотоцикл с 210 л.с. и электронной подвеской. Доминирует на треке и на дороге." },

                // ===== Mercedes-Benz =====
                new Car { Brand = "Mercedes-Benz", Model = "S-Class S500", Year = 2024, Price = 15_000_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 449, EngineType = "Бензиновый R6 Turbo + EQ Boost", EngineVolume = 3.0, Transmission = "Автомат 9-ст", FuelType = "Бензин АИ-98", FuelConsumption = 9.1, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Чёрный", Acceleration0to100 = 4.9, Weight = 2110, Country = "Германия", Description = "Mercedes S-Class — эталон автомобильной роскоши. MBUX с дополненной реальностью, пневмоподвеска, массаж и аромат в салоне." },
                new Car { Brand = "Mercedes-Benz", Model = "AMG GT 63 S", Year = 2024, Price = 18_500_000m, LicenseCategory = "B", MaxSpeedKmh = 315, HorsePower = 639, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 4.0, Transmission = "Автомат 9-ст", FuelType = "Бензин АИ-98", FuelConsumption = 12.5, Seats = 5, BodyType = "Спорткар", DriveType = "Полный", Color = "Серый", Acceleration0to100 = 3.2, Weight = 2150, Country = "Германия", Description = "Mercedes-AMG GT 63 S — суперседан с 639 л.с. и разгоном до 100 за 3.2 секунды. Роскошь и мощь в одном кузове." },
                new Car { Brand = "Mercedes-Benz", Model = "GLE 450", Year = 2024, Price = 10_200_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 367, EngineType = "Бензиновый R6 Turbo", EngineVolume = 3.0, Transmission = "Автомат 9-ст", FuelType = "Бензин АИ-95", FuelConsumption = 9.5, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Белый", Acceleration0to100 = 5.7, Weight = 2195, Country = "Германия", Description = "Mercedes GLE — роскошный кроссовер с E-Active Body Control, 12.3\" MBUX и вместительным салоном для всей семьи." },
                new Car { Brand = "Mercedes-Benz", Model = "EQS 580", Year = 2024, Price = 14_900_000m, LicenseCategory = "B", MaxSpeedKmh = 210, HorsePower = 523, EngineType = "Электрический", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Серебристый", Acceleration0to100 = 4.3, Weight = 2585, Country = "Германия", Description = "Mercedes EQS — электрический флагман с гиперэкраном MBUX 56\", запасом хода 770 км и рекордным Cx=0.20." },
                new Car { Brand = "Mercedes-Benz", Model = "G-Class G63 AMG", Year = 2024, Price = 25_000_000m, LicenseCategory = "B", MaxSpeedKmh = 220, HorsePower = 585, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 4.0, Transmission = "Автомат 9-ст", FuelType = "Бензин АИ-98", FuelConsumption = 16.1, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Чёрный", Acceleration0to100 = 4.5, Weight = 2560, Country = "Германия", Description = "Mercedes G63 AMG — легендарный внедорожник с V8 585 л.с. Иконический дизайн с 1979 года, три блокировки дифференциалов." },

                // ===== Audi =====
                new Car { Brand = "Audi", Model = "RS7 Sportback", Year = 2024, Price = 14_500_000m, LicenseCategory = "B", MaxSpeedKmh = 305, HorsePower = 600, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 4.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 11.5, Seats = 5, BodyType = "Спорткар", DriveType = "Полный", Color = "Серый", Acceleration0to100 = 3.6, Weight = 2065, Country = "Германия", Description = "Audi RS7 — стремительный фастбэк с 600 л.с. и quattro. Сочетание агрессивного дизайна, невероятной динамики и повседневного комфорта." },
                new Car { Brand = "Audi", Model = "Q8 55 TFSI", Year = 2024, Price = 11_000_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 340, EngineType = "Бензиновый V6 Turbo", EngineVolume = 3.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-95", FuelConsumption = 10.1, Seats = 5, BodyType = "Кроссовер", DriveType = "Полный", Color = "Синий", Acceleration0to100 = 5.6, Weight = 2175, Country = "Германия", Description = "Audi Q8 — купе-кроссовер с виртуальным кокпитом, тремя дисплеями MMI touch и пневмоподвеской. Стиль без компромиссов." },
                new Car { Brand = "Audi", Model = "e-tron GT RS", Year = 2024, Price = 16_000_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 646, EngineType = "Электрический", EngineVolume = 0.0, Transmission = "2-ст автомат", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Спорткар", DriveType = "Полный", Color = "Зелёный", Acceleration0to100 = 3.3, Weight = 2347, Country = "Германия", Description = "Audi e-tron GT RS — электрический суперкар с 646 л.с. Платформа Porsche Taycan, дизайн будущего и нулевые выбросы." },
                new Car { Brand = "Audi", Model = "A4 45 TFSI", Year = 2024, Price = 4_500_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 265, EngineType = "Бензиновый R4 Turbo", EngineVolume = 2.0, Transmission = "Автомат 7-ст", FuelType = "Бензин АИ-95", FuelConsumption = 7.1, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Белый", Acceleration0to100 = 5.8, Weight = 1605, Country = "Германия", Description = "Audi A4 — классический бизнес-седан с quattro, виртуальным кокпитом и безупречной эргономикой. Надёжность и технологии." },

                // ===== Porsche =====
                new Car { Brand = "Porsche", Model = "911 Carrera S", Year = 2024, Price = 14_800_000m, LicenseCategory = "B", MaxSpeedKmh = 308, HorsePower = 450, EngineType = "Бензиновый B6 Twin-Turbo", EngineVolume = 3.0, Transmission = "PDK 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 10.1, Seats = 4, BodyType = "Спорткар", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 3.5, Weight = 1515, Country = "Германия", Description = "Porsche 911 — живая легенда. Оппозитный двигатель, задний привод и характер, выкованный на Нюрбургринге с 1963 года." },
                new Car { Brand = "Porsche", Model = "Cayenne Turbo GT", Year = 2024, Price = 22_000_000m, LicenseCategory = "B", MaxSpeedKmh = 300, HorsePower = 640, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 4.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 14.1, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Жёлтый", Acceleration0to100 = 3.3, Weight = 2245, Country = "Германия", Description = "Porsche Cayenne Turbo GT — самый быстрый SUV от Porsche. 640 л.с., рекорд Нюрбургринга среди кроссоверов." },
                new Car { Brand = "Porsche", Model = "Taycan Turbo S", Year = 2024, Price = 19_500_000m, LicenseCategory = "B", MaxSpeedKmh = 260, HorsePower = 761, EngineType = "Электрический", EngineVolume = 0.0, Transmission = "2-ст автомат", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Спорткар", DriveType = "Полный", Color = "Белый", Acceleration0to100 = 2.8, Weight = 2295, Country = "Германия", Description = "Porsche Taycan Turbo S — электрический суперседан с 761 л.с. Разгон 0-100 за 2.8 сек, запас хода до 507 км." },
                new Car { Brand = "Porsche", Model = "Panamera 4S", Year = 2024, Price = 13_000_000m, LicenseCategory = "B", MaxSpeedKmh = 296, HorsePower = 480, EngineType = "Бензиновый V6 Biturbo", EngineVolume = 2.9, Transmission = "PDK 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 10.6, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Серый", Acceleration0to100 = 3.7, Weight = 2015, Country = "Германия", Description = "Porsche Panamera — спортивный бизнес-седан с характером 911. Активная аэродинамика и трёхкамерная пневмоподвеска." },

                // ===== Lamborghini =====
                new Car { Brand = "Lamborghini", Model = "Huracán EVO", Year = 2024, Price = 28_000_000m, LicenseCategory = "B", MaxSpeedKmh = 325, HorsePower = 640, EngineType = "Бензиновый V10", EngineVolume = 5.2, Transmission = "Робот 7-ст", FuelType = "Бензин АИ-98", FuelConsumption = 14.7, Seats = 2, BodyType = "Суперкар", DriveType = "Полный", Color = "Жёлтый", Acceleration0to100 = 2.9, Weight = 1422, Country = "Италия", Description = "Lamborghini Huracán EVO — суперкар с атмосферным V10 и системой LDVI. Звук мотора покоряет с первых оборотов." },
                new Car { Brand = "Lamborghini", Model = "Urus Performante", Year = 2024, Price = 32_000_000m, LicenseCategory = "B", MaxSpeedKmh = 306, HorsePower = 666, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 4.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 14.0, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Зелёный", Acceleration0to100 = 3.3, Weight = 2150, Country = "Италия", Description = "Lamborghini Urus Performante — самый быстрый SUV в мире. 666 л.с., углеродный обвес и рёв V8 на каждом светофоре." },
                new Car { Brand = "Lamborghini", Model = "Revuelto", Year = 2024, Price = 65_000_000m, LicenseCategory = "B", MaxSpeedKmh = 350, HorsePower = 1015, EngineType = "Гибрид V12 + 3 электромотора", EngineVolume = 6.5, Transmission = "Робот 8-ст", FuelType = "Гибрид", FuelConsumption = 11.5, Seats = 2, BodyType = "Гиперкар", DriveType = "Полный", Color = "Оранжевый", Acceleration0to100 = 2.5, Weight = 1772, Country = "Италия", Description = "Lamborghini Revuelto — первый гибрид от Lamborghini. V12 + 3 электромотора = 1015 л.с. Наследник Aventador." },

                // ===== Ferrari =====
                new Car { Brand = "Ferrari", Model = "F8 Tributo", Year = 2024, Price = 30_000_000m, LicenseCategory = "B", MaxSpeedKmh = 340, HorsePower = 720, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 3.9, Transmission = "Робот 7-ст", FuelType = "Бензин АИ-98", FuelConsumption = 11.4, Seats = 2, BodyType = "Суперкар", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 2.9, Weight = 1330, Country = "Италия", Description = "Ferrari F8 Tributo — дань уважения лучшему V8 в истории. 720 л.с., аэродинамика от F1 и чистый восторг от вождения." },
                new Car { Brand = "Ferrari", Model = "Roma", Year = 2024, Price = 25_000_000m, LicenseCategory = "B", MaxSpeedKmh = 320, HorsePower = 620, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 3.9, Transmission = "Робот 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 10.6, Seats = 4, BodyType = "Купе", DriveType = "Задний", Color = "Серый", Acceleration0to100 = 3.4, Weight = 1472, Country = "Италия", Description = "Ferrari Roma — la nuova dolce vita. Элегантный GT с 620-сильным V8, двойным кокпитом и итальянским шиком." },
                new Car { Brand = "Ferrari", Model = "296 GTB", Year = 2024, Price = 35_000_000m, LicenseCategory = "B", MaxSpeedKmh = 330, HorsePower = 830, EngineType = "Гибрид V6 Turbo + электромотор", EngineVolume = 3.0, Transmission = "Робот 8-ст", FuelType = "Гибрид", FuelConsumption = 6.4, Seats = 2, BodyType = "Суперкар", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 2.9, Weight = 1470, Country = "Италия", Description = "Ferrari 296 GTB — гибридный суперкар с 830 л.с. V6 с электрической тягой, первый в истории Ferrari." },
                new Car { Brand = "Ferrari", Model = "SF90 Stradale", Year = 2024, Price = 55_000_000m, LicenseCategory = "B", MaxSpeedKmh = 340, HorsePower = 1000, EngineType = "Гибрид V8 Turbo + 3 электромотора", EngineVolume = 4.0, Transmission = "Робот 8-ст", FuelType = "Гибрид", FuelConsumption = 7.9, Seats = 2, BodyType = "Гиперкар", DriveType = "Полный", Color = "Красный", Acceleration0to100 = 2.5, Weight = 1570, Country = "Италия", Description = "Ferrari SF90 Stradale — 1000 л.с. гиперкар с технологиями F1. Первый полноприводный Ferrari с электрическим передним мостом." },

                // ===== Toyota =====
                new Car { Brand = "Toyota", Model = "Camry 3.5", Year = 2024, Price = 3_200_000m, LicenseCategory = "B", MaxSpeedKmh = 235, HorsePower = 249, EngineType = "Бензиновый V6", EngineVolume = 3.5, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-92", FuelConsumption = 9.3, Seats = 5, BodyType = "Седан", DriveType = "Передний", Color = "Белый", Acceleration0to100 = 7.1, Weight = 1590, Country = "Япония", Description = "Toyota Camry — самый продаваемый бизнес-седан. Надёжность Toyota, просторный салон и экономичный V6." },
                new Car { Brand = "Toyota", Model = "Land Cruiser 300", Year = 2024, Price = 7_500_000m, LicenseCategory = "B", MaxSpeedKmh = 210, HorsePower = 415, EngineType = "Бензиновый V6 Twin-Turbo", EngineVolume = 3.5, Transmission = "Автомат 10-ст", FuelType = "Бензин АИ-95", FuelConsumption = 11.5, Seats = 7, BodyType = "Внедорожник", DriveType = "Полный", Color = "Серебристый", Acceleration0to100 = 6.7, Weight = 2490, Country = "Япония", Description = "Toyota Land Cruiser 300 — легенда бездорожья. TNGA-F платформа, 415 л.с. и непревзойдённая надёжность с 1951 года." },
                new Car { Brand = "Toyota", Model = "GR Supra 3.0", Year = 2024, Price = 6_200_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 387, EngineType = "Бензиновый R6 Turbo", EngineVolume = 3.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-95", FuelConsumption = 8.9, Seats = 2, BodyType = "Купе", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 4.1, Weight = 1540, Country = "Япония", Description = "Toyota GR Supra — возрождение легенды. Рядная шестёрка BMW, задний привод и идеальная развесовка 50:50." },
                new Car { Brand = "Toyota", Model = "RAV4 2.5 Hybrid", Year = 2024, Price = 3_800_000m, LicenseCategory = "B", MaxSpeedKmh = 180, HorsePower = 222, EngineType = "Гибрид R4", EngineVolume = 2.5, Transmission = "Вариатор", FuelType = "Гибрид", FuelConsumption = 5.6, Seats = 5, BodyType = "Кроссовер", DriveType = "Полный", Color = "Зелёный", Acceleration0to100 = 7.8, Weight = 1700, Country = "Япония", Description = "Toyota RAV4 Hybrid — самый популярный кроссовер мира. Гибридная система, полный привод E-Four и 5.6 л/100 км." },

                // ===== Lexus =====
                new Car { Brand = "Lexus", Model = "LS 500h", Year = 2024, Price = 10_000_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 354, EngineType = "Гибрид V6", EngineVolume = 3.5, Transmission = "Автомат 10-ст", FuelType = "Гибрид", FuelConsumption = 7.6, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Чёрный", Acceleration0to100 = 5.4, Weight = 2260, Country = "Япония", Description = "Lexus LS — японский ответ S-Class. Ручной шов ошибори, шпон бамбука и тишина в салоне как в лучших отелях." },
                new Car { Brand = "Lexus", Model = "LX 600", Year = 2024, Price = 12_000_000m, LicenseCategory = "B", MaxSpeedKmh = 210, HorsePower = 415, EngineType = "Бензиновый V6 Twin-Turbo", EngineVolume = 3.5, Transmission = "Автомат 10-ст", FuelType = "Бензин АИ-95", FuelConsumption = 12.1, Seats = 7, BodyType = "Внедорожник", DriveType = "Полный", Color = "Белый", Acceleration0to100 = 6.9, Weight = 2670, Country = "Япония", Description = "Lexus LX 600 — роскошный внедорожник на базе Land Cruiser 300. Кожа semi-aniline, 25\" дисплей Mark Levinson." },
                new Car { Brand = "Lexus", Model = "LC 500", Year = 2024, Price = 11_500_000m, LicenseCategory = "B", MaxSpeedKmh = 270, HorsePower = 477, EngineType = "Бензиновый V8", EngineVolume = 5.0, Transmission = "Автомат 10-ст", FuelType = "Бензин АИ-98", FuelConsumption = 11.6, Seats = 4, BodyType = "Купе", DriveType = "Задний", Color = "Синий", Acceleration0to100 = 4.7, Weight = 1935, Country = "Япония", Description = "Lexus LC 500 — произведение искусства на колёсах. Атмосферный V8, 10-ступенчатый автомат и дизайн с выставки." },

                // ===== Honda =====
                new Car { Brand = "Honda", Model = "Civic Type R", Year = 2024, Price = 5_200_000m, LicenseCategory = "B", MaxSpeedKmh = 275, HorsePower = 329, EngineType = "Бензиновый R4 Turbo VTEC", EngineVolume = 2.0, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-95", FuelConsumption = 8.0, Seats = 5, BodyType = "Хэтчбек", DriveType = "Передний", Color = "Белый", Acceleration0to100 = 5.4, Weight = 1420, Country = "Япония", Description = "Honda Civic Type R — рекордсмен Нюрбургринга среди переднеприводных. VTEC Turbo 329 л.с. и адаптивная подвеска." },
                new Car { Brand = "Honda", Model = "CR-V Hybrid", Year = 2024, Price = 3_500_000m, LicenseCategory = "B", MaxSpeedKmh = 190, HorsePower = 204, EngineType = "Гибрид R4", EngineVolume = 2.0, Transmission = "Вариатор", FuelType = "Гибрид", FuelConsumption = 5.3, Seats = 5, BodyType = "Кроссовер", DriveType = "Полный", Color = "Серый", Acceleration0to100 = 8.6, Weight = 1670, Country = "Япония", Description = "Honda CR-V Hybrid — компактный кроссовер с гибридной установкой e:HEV. Экономичность, простор и технологичность." },

                // ===== Nissan =====
                new Car { Brand = "Nissan", Model = "GT-R Nismo", Year = 2024, Price = 18_000_000m, LicenseCategory = "B", MaxSpeedKmh = 315, HorsePower = 600, EngineType = "Бензиновый V6 Twin-Turbo", EngineVolume = 3.8, Transmission = "Робот 6-ст", FuelType = "Бензин АИ-98", FuelConsumption = 12.8, Seats = 4, BodyType = "Спорткар", DriveType = "Полный", Color = "Белый", Acceleration0to100 = 2.5, Weight = 1720, Country = "Япония", Description = "Nissan GT-R Nismo — «Годзилла». 600 л.с. ручной сборки, ATTESA E-TS полный привод и репутация убийцы суперкаров." },
                new Car { Brand = "Nissan", Model = "Patrol V8", Year = 2024, Price = 6_500_000m, LicenseCategory = "B", MaxSpeedKmh = 210, HorsePower = 405, EngineType = "Бензиновый V8", EngineVolume = 5.6, Transmission = "Автомат 7-ст", FuelType = "Бензин АИ-95", FuelConsumption = 14.5, Seats = 8, BodyType = "Внедорожник", DriveType = "Полный", Color = "Серебристый", Acceleration0to100 = 6.6, Weight = 2740, Country = "Япония", Description = "Nissan Patrol — флагманский внедорожник с V8 5.6 л. Гидравлическая подвеска и 8 мест для больших путешествий." },

                // ===== Volkswagen =====
                new Car { Brand = "Volkswagen", Model = "Golf R", Year = 2024, Price = 4_800_000m, LicenseCategory = "B", MaxSpeedKmh = 270, HorsePower = 333, EngineType = "Бензиновый R4 Turbo", EngineVolume = 2.0, Transmission = "Робот DSG 7-ст", FuelType = "Бензин АИ-95", FuelConsumption = 7.6, Seats = 5, BodyType = "Хэтчбек", DriveType = "Полный", Color = "Синий", Acceleration0to100 = 4.7, Weight = 1480, Country = "Германия", Description = "VW Golf R — 333 л.с. хот-хэтч с полным приводом 4Motion и R-Performance Torque Vectoring. Ракета на каждый день." },
                new Car { Brand = "Volkswagen", Model = "Touareg V6", Year = 2024, Price = 6_800_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 340, EngineType = "Бензиновый V6 Turbo", EngineVolume = 3.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-95", FuelConsumption = 9.8, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Чёрный", Acceleration0to100 = 5.9, Weight = 2150, Country = "Германия", Description = "VW Touareg — премиальный SUV с IQ.Light матричными фарами, пневмоподвеской и Innovision Cockpit." },
                new Car { Brand = "Volkswagen", Model = "ID.4 GTX", Year = 2024, Price = 5_200_000m, LicenseCategory = "B", MaxSpeedKmh = 180, HorsePower = 299, EngineType = "Электрический", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Кроссовер", DriveType = "Полный", Color = "Серый", Acceleration0to100 = 6.2, Weight = 2224, Country = "Германия", Description = "VW ID.4 GTX — электрический кроссовер с двумя моторами. Запас хода 480 км, платформа MEB и OTA-обновления." },

                // ===== Ford =====
                new Car { Brand = "Ford", Model = "Mustang GT", Year = 2024, Price = 5_500_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 486, EngineType = "Бензиновый V8 Coyote", EngineVolume = 5.0, Transmission = "Автомат 10-ст", FuelType = "Бензин АИ-95", FuelConsumption = 12.4, Seats = 4, BodyType = "Купе", DriveType = "Задний", Color = "Синий", Acceleration0to100 = 4.2, Weight = 1735, Country = "США", Description = "Ford Mustang GT — 60 лет американской мускульной мощи. V8 Coyote 486 л.с. и электронный дифференциал MagneRide." },
                new Car { Brand = "Ford", Model = "F-150 Raptor", Year = 2024, Price = 8_500_000m, LicenseCategory = "B", MaxSpeedKmh = 175, HorsePower = 450, EngineType = "Бензиновый V6 EcoBoost Turbo", EngineVolume = 3.5, Transmission = "Автомат 10-ст", FuelType = "Бензин АИ-95", FuelConsumption = 16.0, Seats = 5, BodyType = "Пикап", DriveType = "Полный", Color = "Оранжевый", Acceleration0to100 = 5.2, Weight = 2710, Country = "США", Description = "Ford F-150 Raptor — внедорожный пикап с FOX амортизаторами, 450 л.с. и 37\" шинами. Покоряет пустыни и бездорожье." },
                new Car { Brand = "Ford", Model = "Bronco Raptor", Year = 2024, Price = 7_200_000m, LicenseCategory = "B", MaxSpeedKmh = 170, HorsePower = 418, EngineType = "Бензиновый V6 EcoBoost Turbo", EngineVolume = 3.0, Transmission = "Автомат 10-ст", FuelType = "Бензин АИ-95", FuelConsumption = 15.0, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Жёлтый", Acceleration0to100 = 5.9, Weight = 2580, Country = "США", Description = "Ford Bronco Raptor — экстремальный вездеход с HOSS 4.0 подвеской. Ширина 2180 мм для уверенности на бездорожье." },

                // ===== Chevrolet =====
                new Car { Brand = "Chevrolet", Model = "Corvette Stingray", Year = 2024, Price = 11_000_000m, LicenseCategory = "B", MaxSpeedKmh = 312, HorsePower = 495, EngineType = "Бензиновый V8 LT2", EngineVolume = 6.2, Transmission = "Робот DCT 8-ст", FuelType = "Бензин АИ-95", FuelConsumption = 12.0, Seats = 2, BodyType = "Спорткар", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 2.9, Weight = 1530, Country = "США", Description = "Chevrolet Corvette C8 — первый среднемоторный Corvette в истории. 495 л.с. V8 и суперкар-динамика по цене премиума." },
                new Car { Brand = "Chevrolet", Model = "Tahoe RST", Year = 2024, Price = 7_500_000m, LicenseCategory = "B", MaxSpeedKmh = 190, HorsePower = 420, EngineType = "Бензиновый V8", EngineVolume = 6.2, Transmission = "Автомат 10-ст", FuelType = "Бензин АИ-95", FuelConsumption = 14.7, Seats = 8, BodyType = "Внедорожник", DriveType = "Полный", Color = "Чёрный", Acceleration0to100 = 6.0, Weight = 2620, Country = "США", Description = "Chevrolet Tahoe — полноразмерный SUV с V8 6.2 л. Magnetic Ride Control, 8 мест и независимая задняя подвеска." },

                // ===== Tesla =====
                new Car { Brand = "Tesla", Model = "Model S Plaid", Year = 2024, Price = 12_000_000m, LicenseCategory = "B", MaxSpeedKmh = 322, HorsePower = 1020, EngineType = "Электрический (3 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Белый", Acceleration0to100 = 2.1, Weight = 2162, Country = "США", Description = "Tesla Model S Plaid — самый быстрый серийный электромобиль. 1020 л.с., 0-100 за 2.1 сек и штурвал вместо руля." },
                new Car { Brand = "Tesla", Model = "Model X Plaid", Year = 2024, Price = 13_500_000m, LicenseCategory = "B", MaxSpeedKmh = 262, HorsePower = 1020, EngineType = "Электрический (3 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 7, BodyType = "Внедорожник", DriveType = "Полный", Color = "Красный", Acceleration0to100 = 2.5, Weight = 2455, Country = "США", Description = "Tesla Model X Plaid — электрический SUV с крыльями сокола. 1020 л.с. и 7 мест с HEPA-фильтрацией воздуха." },
                new Car { Brand = "Tesla", Model = "Model 3 Performance", Year = 2024, Price = 5_800_000m, LicenseCategory = "B", MaxSpeedKmh = 262, HorsePower = 510, EngineType = "Электрический (2 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Серый", Acceleration0to100 = 3.3, Weight = 1836, Country = "США", Description = "Tesla Model 3 Performance — спортивный электроседан с 510 л.с. Автопилот, OTA-обновления и запас хода 528 км." },
                new Car { Brand = "Tesla", Model = "Cybertruck", Year = 2024, Price = 9_000_000m, LicenseCategory = "B", MaxSpeedKmh = 210, HorsePower = 845, EngineType = "Электрический (3 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Пикап", DriveType = "Полный", Color = "Серебристый", Acceleration0to100 = 2.6, Weight = 3104, Country = "США", Description = "Tesla Cybertruck — бронированный электропикап из нержавеющей стали. 845 л.с., адаптивная пневмоподвеска." },

                // ===== Rolls-Royce =====
                new Car { Brand = "Rolls-Royce", Model = "Phantom VIII", Year = 2024, Price = 55_000_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 571, EngineType = "Бензиновый V12 Biturbo", EngineVolume = 6.75, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 15.0, Seats = 5, BodyType = "Седан", DriveType = "Задний", Color = "Чёрный", Acceleration0to100 = 5.3, Weight = 2560, Country = "Великобритания", Description = "Rolls-Royce Phantom — вершина автомобильной роскоши. Звёздное небо на потолке, Gallery дашборд и абсолютная тишина." },
                new Car { Brand = "Rolls-Royce", Model = "Cullinan Black Badge", Year = 2024, Price = 52_000_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 600, EngineType = "Бензиновый V12 Biturbo", EngineVolume = 6.75, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 15.7, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Чёрный", Acceleration0to100 = 5.0, Weight = 2752, Country = "Великобритания", Description = "Rolls-Royce Cullinan Black Badge — самый роскошный SUV на планете. V12 600 л.с. и тёмная сторона величия." },
                new Car { Brand = "Rolls-Royce", Model = "Spectre", Year = 2024, Price = 45_000_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 585, EngineType = "Электрический", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 4, BodyType = "Купе", DriveType = "Полный", Color = "Серебристый", Acceleration0to100 = 4.5, Weight = 2975, Country = "Великобритания", Description = "Rolls-Royce Spectre — первый электрический Rolls-Royce. 585 л.с., 520 км запас хода и ковёр электрической тишины." },

                // ===== Bentley =====
                new Car { Brand = "Bentley", Model = "Continental GT Speed", Year = 2024, Price = 28_000_000m, LicenseCategory = "B", MaxSpeedKmh = 335, HorsePower = 659, EngineType = "Бензиновый W12 Biturbo", EngineVolume = 6.0, Transmission = "Робот DCT 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 14.4, Seats = 4, BodyType = "Купе", DriveType = "Полный", Color = "Зелёный", Acceleration0to100 = 3.5, Weight = 2273, Country = "Великобритания", Description = "Bentley Continental GT Speed — 659 л.с. W12 GT. Ротируемый органайзер из 3 панелей, стёжка Diamond-in-Diamond." },
                new Car { Brand = "Bentley", Model = "Bentayga V8", Year = 2024, Price = 22_000_000m, LicenseCategory = "B", MaxSpeedKmh = 290, HorsePower = 550, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 4.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 13.2, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Белый", Acceleration0to100 = 4.4, Weight = 2440, Country = "Великобритания", Description = "Bentley Bentayga V8 — ультра-люксовый SUV с 550 л.с. V8. 22 способа регулировки кресел и часы Breitling на панели." },
                new Car { Brand = "Bentley", Model = "Flying Spur V8", Year = 2024, Price = 24_000_000m, LicenseCategory = "B", MaxSpeedKmh = 318, HorsePower = 550, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 4.0, Transmission = "Робот DCT 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 12.8, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Серый", Acceleration0to100 = 4.0, Weight = 2340, Country = "Великобритания", Description = "Bentley Flying Spur — спортивный лимузин с сенсорным кокпитом. 550 л.с. V8 и ворлд-класс задний комфорт." },

                // ===== Aston Martin =====
                new Car { Brand = "Aston Martin", Model = "DB12", Year = 2024, Price = 27_000_000m, LicenseCategory = "B", MaxSpeedKmh = 325, HorsePower = 680, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 4.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 12.3, Seats = 4, BodyType = "Купе", DriveType = "Задний", Color = "Серебристый", Acceleration0to100 = 3.6, Weight = 1685, Country = "Великобритания", Description = "Aston Martin DB12 — первый в мире Super Tourer. 680 л.с. V8, карбон-керамические тормоза и дух Джеймса Бонда." },
                new Car { Brand = "Aston Martin", Model = "Vantage V8", Year = 2024, Price = 20_000_000m, LicenseCategory = "B", MaxSpeedKmh = 325, HorsePower = 665, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 4.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 11.8, Seats = 2, BodyType = "Спорткар", DriveType = "Задний", Color = "Зелёный", Acceleration0to100 = 3.4, Weight = 1605, Country = "Великобритания", Description = "Aston Martin Vantage — чистый спорткар. 665 л.с. Mercedes-AMG V8, электронный дифференциал E-Diff и минимализм." },

                // ===== McLaren =====
                new Car { Brand = "McLaren", Model = "750S", Year = 2024, Price = 35_000_000m, LicenseCategory = "B", MaxSpeedKmh = 332, HorsePower = 750, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 4.0, Transmission = "Робот SSG 7-ст", FuelType = "Бензин АИ-98", FuelConsumption = 11.7, Seats = 2, BodyType = "Суперкар", DriveType = "Задний", Color = "Оранжевый", Acceleration0to100 = 2.8, Weight = 1277, Country = "Великобритания", Description = "McLaren 750S — 750 л.с. суперкар с карбоновым монококом. Легче, быстрее и острее чем 720S. Гоночное ДНК F1." },
                new Car { Brand = "McLaren", Model = "Artura", Year = 2024, Price = 30_000_000m, LicenseCategory = "B", MaxSpeedKmh = 330, HorsePower = 680, EngineType = "Гибрид V6 Turbo + электромотор", EngineVolume = 3.0, Transmission = "Робот 8-ст", FuelType = "Гибрид", FuelConsumption = 5.7, Seats = 2, BodyType = "Суперкар", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 3.0, Weight = 1395, Country = "Великобритания", Description = "McLaren Artura — гибридный суперкар нового поколения. V6 Twin-Turbo + E-мотор и платформа McLaren Carbon Lightweight Architecture." },

                // ===== Bugatti =====
                new Car { Brand = "Bugatti", Model = "Chiron Super Sport", Year = 2024, Price = 350_000_000m, LicenseCategory = "B", MaxSpeedKmh = 440, HorsePower = 1600, EngineType = "Бензиновый W16 Quad-Turbo", EngineVolume = 8.0, Transmission = "Робот DSG 7-ст", FuelType = "Бензин АИ-98", FuelConsumption = 35.2, Seats = 2, BodyType = "Гиперкар", DriveType = "Полный", Color = "Синий", Acceleration0to100 = 2.4, Weight = 1995, Country = "Франция", Description = "Bugatti Chiron Super Sport — 1600 л.с. W16 и скорость 440 км/ч. Абсолютный рекорд скорости среди серийных автомобилей." },

                // ===== Pagani =====
                new Car { Brand = "Pagani", Model = "Huayra Roadster BC", Year = 2024, Price = 250_000_000m, LicenseCategory = "B", MaxSpeedKmh = 370, HorsePower = 800, EngineType = "Бензиновый V12 Biturbo (AMG)", EngineVolume = 6.0, Transmission = "Робот 7-ст", FuelType = "Бензин АИ-98", FuelConsumption = 16.5, Seats = 2, BodyType = "Гиперкар", DriveType = "Задний", Color = "Серебристый", Acceleration0to100 = 2.9, Weight = 1250, Country = "Италия", Description = "Pagani Huayra — итальянский гиперкар ручной сборки. Карботитановый кузов, AMG V12 и произведение искусства за рулём." },

                // ===== Koenigsegg =====
                new Car { Brand = "Koenigsegg", Model = "Jesko Absolut", Year = 2024, Price = 300_000_000m, LicenseCategory = "B", MaxSpeedKmh = 531, HorsePower = 1600, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 5.0, Transmission = "Koenigsegg LST 9-ст", FuelType = "Бензин АИ-98", FuelConsumption = 18.0, Seats = 2, BodyType = "Гиперкар", DriveType = "Задний", Color = "Серебристый", Acceleration0to100 = 2.5, Weight = 1420, Country = "Швеция", Description = "Koenigsegg Jesko Absolut — самый быстрый автомобиль в мире. 1600 л.с. на E85 и расчётная скорость 531 км/ч." },

                // ===== Maserati =====
                new Car { Brand = "Maserati", Model = "MC20", Year = 2024, Price = 22_000_000m, LicenseCategory = "B", MaxSpeedKmh = 325, HorsePower = 630, EngineType = "Бензиновый V6 Biturbo Nettuno", EngineVolume = 3.0, Transmission = "Робот DCT 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 11.0, Seats = 2, BodyType = "Суперкар", DriveType = "Задний", Color = "Белый", Acceleration0to100 = 2.9, Weight = 1500, Country = "Италия", Description = "Maserati MC20 — возвращение Maserati в суперкары. Двигатель Nettuno с технологией F1 MTC и карбоновый кузов." },
                new Car { Brand = "Maserati", Model = "Ghibli Trofeo", Year = 2024, Price = 12_000_000m, LicenseCategory = "B", MaxSpeedKmh = 326, HorsePower = 580, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 3.8, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 12.0, Seats = 5, BodyType = "Седан", DriveType = "Задний", Color = "Синий", Acceleration0to100 = 4.3, Weight = 1969, Country = "Италия", Description = "Maserati Ghibli Trofeo — спортивный бизнес-седан с Ferrari V8. 580 л.с. и итальянский характер в каждом километре." },

                // ===== Hyundai =====
                new Car { Brand = "Hyundai", Model = "Sonata N Line", Year = 2024, Price = 3_100_000m, LicenseCategory = "B", MaxSpeedKmh = 240, HorsePower = 290, EngineType = "Бензиновый R4 Turbo", EngineVolume = 2.5, Transmission = "Робот DCT 8-ст", FuelType = "Бензин АИ-95", FuelConsumption = 8.9, Seats = 5, BodyType = "Седан", DriveType = "Передний", Color = "Красный", Acceleration0to100 = 6.0, Weight = 1565, Country = "Южная Корея", Description = "Hyundai Sonata N Line — спортивный седан с 290 л.с. N-настройка подвески, выхлопа и рулевого управления." },
                new Car { Brand = "Hyundai", Model = "Tucson N Line", Year = 2024, Price = 3_400_000m, LicenseCategory = "B", MaxSpeedKmh = 215, HorsePower = 265, EngineType = "Бензиновый R4 Turbo", EngineVolume = 2.5, Transmission = "Робот DCT 8-ст", FuelType = "Бензин АИ-95", FuelConsumption = 9.2, Seats = 5, BodyType = "Кроссовер", DriveType = "Полный", Color = "Серый", Acceleration0to100 = 7.0, Weight = 1660, Country = "Южная Корея", Description = "Hyundai Tucson — параметрический дизайн и передовые технологии. HTRAC полный привод и SmartSense безопасность." },
                new Car { Brand = "Hyundai", Model = "IONIQ 5 N", Year = 2024, Price = 5_500_000m, LicenseCategory = "B", MaxSpeedKmh = 260, HorsePower = 650, EngineType = "Электрический (2 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Кроссовер", DriveType = "Полный", Color = "Синий", Acceleration0to100 = 3.4, Weight = 2210, Country = "Южная Корея", Description = "Hyundai IONIQ 5 N — первый электрический N. 650 л.с., N e-shift имитация переключений и N Drift Optimizer." },

                // ===== Kia =====
                new Car { Brand = "Kia", Model = "EV6 GT", Year = 2024, Price = 5_800_000m, LicenseCategory = "B", MaxSpeedKmh = 260, HorsePower = 585, EngineType = "Электрический (2 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Кроссовер", DriveType = "Полный", Color = "Зелёный", Acceleration0to100 = 3.5, Weight = 2205, Country = "Южная Корея", Description = "Kia EV6 GT — 585 л.с. электрический GT от Kia. 800V архитектура, зарядка 10-80% за 18 минут и дрифт-режим." },
                new Car { Brand = "Kia", Model = "K5 GT", Year = 2024, Price = 2_800_000m, LicenseCategory = "B", MaxSpeedKmh = 240, HorsePower = 290, EngineType = "Бензиновый R4 Turbo", EngineVolume = 2.5, Transmission = "Робот DCT 8-ст", FuelType = "Бензин АИ-95", FuelConsumption = 9.0, Seats = 5, BodyType = "Седан", DriveType = "Передний", Color = "Белый", Acceleration0to100 = 6.0, Weight = 1555, Country = "Южная Корея", Description = "Kia K5 GT — стильный фастбэк-седан с 290 л.с. Дизайн от Петера Шрайера и лучшее соотношение цена/качество." },

                // ===== Volvo =====
                new Car { Brand = "Volvo", Model = "XC90 Recharge", Year = 2024, Price = 8_500_000m, LicenseCategory = "B", MaxSpeedKmh = 180, HorsePower = 462, EngineType = "Гибрид R4 Turbo + электромотор", EngineVolume = 2.0, Transmission = "Автомат 8-ст", FuelType = "Гибрид", FuelConsumption = 2.4, Seats = 7, BodyType = "Внедорожник", DriveType = "Полный", Color = "Серебристый", Acceleration0to100 = 5.4, Weight = 2250, Country = "Швеция", Description = "Volvo XC90 — самый безопасный SUV в мире. 7 мест, Bowers & Wilkins акустика и система предотвращения столкновений." },
                new Car { Brand = "Volvo", Model = "S60 T8 Polestar", Year = 2024, Price = 5_500_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 405, EngineType = "Гибрид R4 Turbo + электромотор", EngineVolume = 2.0, Transmission = "Автомат 8-ст", FuelType = "Гибрид", FuelConsumption = 2.1, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Синий", Acceleration0to100 = 4.4, Weight = 2010, Country = "Швеция", Description = "Volvo S60 T8 — спортивный гибридный седан с Polestar оптимизацией. 405 л.с. и скандинавский дизайн." },

                // ===== Jaguar =====
                new Car { Brand = "Jaguar", Model = "F-Type R", Year = 2024, Price = 14_000_000m, LicenseCategory = "B", MaxSpeedKmh = 300, HorsePower = 575, EngineType = "Бензиновый V8 Supercharged", EngineVolume = 5.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 11.9, Seats = 2, BodyType = "Спорткар", DriveType = "Полный", Color = "Зелёный", Acceleration0to100 = 3.7, Weight = 1743, Country = "Великобритания", Description = "Jaguar F-Type R — британский спорткар с 575 л.с. V8. Один из самых красивых автомобилей в мире." },

                // ===== Land Rover =====
                new Car { Brand = "Land Rover", Model = "Range Rover SV", Year = 2024, Price = 20_000_000m, LicenseCategory = "B", MaxSpeedKmh = 265, HorsePower = 530, EngineType = "Бензиновый V8 Biturbo", EngineVolume = 4.4, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 13.1, Seats = 4, BodyType = "Внедорожник", DriveType = "Полный", Color = "Коричневый", Acceleration0to100 = 4.6, Weight = 2560, Country = "Великобритания", Description = "Range Rover SV — ультра-люксовый внедорожник. Ceramic Commander Shift, Meridian 3D и индивидуальный задний отсек." },
                new Car { Brand = "Land Rover", Model = "Defender V8", Year = 2024, Price = 14_000_000m, LicenseCategory = "B", MaxSpeedKmh = 240, HorsePower = 525, EngineType = "Бензиновый V8 Supercharged", EngineVolume = 5.0, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 14.2, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Зелёный", Acceleration0to100 = 5.0, Weight = 2420, Country = "Великобритания", Description = "Land Rover Defender V8 — 525 л.с. версия легендарного вездехода. Спортивная подвеска и Terrain Response 2." },

                // ===== Subaru =====
                new Car { Brand = "Subaru", Model = "WRX STI", Year = 2024, Price = 4_500_000m, LicenseCategory = "B", MaxSpeedKmh = 255, HorsePower = 310, EngineType = "Бензиновый B4 Turbo", EngineVolume = 2.4, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-95", FuelConsumption = 10.6, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Синий", Acceleration0to100 = 5.2, Weight = 1590, Country = "Япония", Description = "Subaru WRX STI — раллийная легенда на дорогах. Симметричный полный привод, оппозитный турбо и характер Колина Макрея." },
                new Car { Brand = "Subaru", Model = "Outback 2.5i", Year = 2024, Price = 3_500_000m, LicenseCategory = "B", MaxSpeedKmh = 190, HorsePower = 188, EngineType = "Бензиновый B4", EngineVolume = 2.5, Transmission = "Вариатор", FuelType = "Бензин АИ-92", FuelConsumption = 8.0, Seats = 5, BodyType = "Кроссовер", DriveType = "Полный", Color = "Зелёный", Acceleration0to100 = 9.4, Weight = 1640, Country = "Япония", Description = "Subaru Outback — универсальный кроссовер с 220 мм клиренса. EyeSight безопасность и симметричный AWD." },

                // ===== Mazda =====
                new Car { Brand = "Mazda", Model = "MX-5 Miata", Year = 2024, Price = 3_200_000m, LicenseCategory = "B", MaxSpeedKmh = 219, HorsePower = 184, EngineType = "Бензиновый R4 SkyActiv-G", EngineVolume = 2.0, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-95", FuelConsumption = 7.2, Seats = 2, BodyType = "Родстер", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 6.5, Weight = 1058, Country = "Япония", Description = "Mazda MX-5 — самый продаваемый родстер в мире. 1058 кг, задний привод и удовольствие от вождения в чистом виде." },
                new Car { Brand = "Mazda", Model = "CX-9 Signature", Year = 2024, Price = 4_800_000m, LicenseCategory = "B", MaxSpeedKmh = 200, HorsePower = 231, EngineType = "Бензиновый R4 SkyActiv-G Turbo", EngineVolume = 2.5, Transmission = "Автомат 6-ст", FuelType = "Бензин АИ-95", FuelConsumption = 10.2, Seats = 7, BodyType = "Кроссовер", DriveType = "Полный", Color = "Коричневый", Acceleration0to100 = 7.3, Weight = 1930, Country = "Япония", Description = "Mazda CX-9 — премиальный 7-местный кроссовер. KODO дизайн, натуральное дерево Rosa и i-ACTIV полный привод." },

                // ===== Mitsubishi =====
                new Car { Brand = "Mitsubishi", Model = "Outlander PHEV", Year = 2024, Price = 3_800_000m, LicenseCategory = "B", MaxSpeedKmh = 170, HorsePower = 248, EngineType = "Гибрид R4 + 2 электромотора", EngineVolume = 2.4, Transmission = "Вариатор", FuelType = "Гибрид", FuelConsumption = 2.0, Seats = 7, BodyType = "Кроссовер", DriveType = "Полный", Color = "Белый", Acceleration0to100 = 7.9, Weight = 2005, Country = "Япония", Description = "Mitsubishi Outlander PHEV — подзаряжаемый гибрид с полным приводом S-AWC. 87 км на электротяге и 7 мест." },

                // ===== Alfa Romeo =====
                new Car { Brand = "Alfa Romeo", Model = "Giulia Quadrifoglio", Year = 2024, Price = 10_500_000m, LicenseCategory = "B", MaxSpeedKmh = 307, HorsePower = 510, EngineType = "Бензиновый V6 Biturbo", EngineVolume = 2.9, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-98", FuelConsumption = 10.5, Seats = 5, BodyType = "Седан", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 3.9, Weight = 1580, Country = "Италия", Description = "Alfa Romeo Giulia QV — Ferrari V6 в седане. 510 л.с., карбоновый карданный вал и итальянская страсть в каждой детали." },

                // ===== Genesis =====
                new Car { Brand = "Genesis", Model = "G90 3.5T", Year = 2024, Price = 8_000_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 409, EngineType = "Бензиновый V6 Twin-Turbo", EngineVolume = 3.5, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-95", FuelConsumption = 10.2, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Чёрный", Acceleration0to100 = 5.1, Weight = 2165, Country = "Южная Корея", Description = "Genesis G90 — корейский ответ Mercedes S-Class. 409 л.с. V6, конфигурация 2 задних VIP-кресла и дизайн двух линий." },
                new Car { Brand = "Genesis", Model = "GV80 Coupe", Year = 2024, Price = 7_500_000m, LicenseCategory = "B", MaxSpeedKmh = 240, HorsePower = 409, EngineType = "Бензиновый V6 Twin-Turbo", EngineVolume = 3.5, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-95", FuelConsumption = 11.0, Seats = 5, BodyType = "Кроссовер", DriveType = "Полный", Color = "Серый", Acceleration0to100 = 5.3, Weight = 2195, Country = "Южная Корея", Description = "Genesis GV80 Coupe — купе-кроссовер с 409 л.с. V6. Bang & Olufsen 3D звук и электронная подвеска Preview." },

                // ===== Dodge =====
                new Car { Brand = "Dodge", Model = "Challenger SRT Hellcat", Year = 2024, Price = 8_000_000m, LicenseCategory = "B", MaxSpeedKmh = 326, HorsePower = 717, EngineType = "Бензиновый V8 HEMI Supercharged", EngineVolume = 6.2, Transmission = "Автомат 8-ст", FuelType = "Бензин АИ-95", FuelConsumption = 16.8, Seats = 5, BodyType = "Купе", DriveType = "Задний", Color = "Оранжевый", Acceleration0to100 = 3.6, Weight = 2020, Country = "США", Description = "Dodge Challenger Hellcat — 717 л.с. суперчарджед HEMI V8. Последний настоящий американский маслкар." },

                // ===== Ducati =====
                new Car { Brand = "Ducati", Model = "Panigale V4 S", Year = 2024, Price = 3_500_000m, LicenseCategory = "A", MaxSpeedKmh = 299, HorsePower = 215, EngineType = "Бензиновый V4 Desmosedici", EngineVolume = 1.1, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-98", FuelConsumption = 7.0, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 3.0, Weight = 195, Country = "Италия", Description = "Ducati Panigale V4 S — MotoGP для дороги. 215 л.с. Desmosedici Stradale, электронная подвеска Öhlins и крылья." },
                new Car { Brand = "Ducati", Model = "Multistrada V4 Rally", Year = 2024, Price = 2_800_000m, LicenseCategory = "A", MaxSpeedKmh = 260, HorsePower = 170, EngineType = "Бензиновый V4 Granturismo", EngineVolume = 1.2, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-95", FuelConsumption = 6.0, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 3.4, Weight = 243, Country = "Италия", Description = "Ducati Multistrada V4 Rally — туристический эндуро с 30 л баком. V4 170 л.с. с интервалом обслуживания 60 000 км." },

                // ===== Kawasaki =====
                new Car { Brand = "Kawasaki", Model = "Ninja ZX-10R", Year = 2024, Price = 2_200_000m, LicenseCategory = "A", MaxSpeedKmh = 299, HorsePower = 203, EngineType = "Бензиновый R4", EngineVolume = 1.0, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-98", FuelConsumption = 6.8, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Зелёный", Acceleration0to100 = 3.1, Weight = 207, Country = "Япония", Description = "Kawasaki Ninja ZX-10R — 6-кратный чемпион WorldSBK. 203 л.с. и электронная система управления мощностью KCMF." },
                new Car { Brand = "Kawasaki", Model = "Z H2 SE", Year = 2024, Price = 2_000_000m, LicenseCategory = "A", MaxSpeedKmh = 280, HorsePower = 200, EngineType = "Бензиновый R4 Supercharged", EngineVolume = 1.0, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-98", FuelConsumption = 7.2, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Серый", Acceleration0to100 = 3.0, Weight = 240, Country = "Япония", Description = "Kawasaki Z H2 SE — нейкед с суперчарджером 200 л.с. Электронная полуактивная подвеска KECS и круиз-контроль." },

                // ===== Yamaha =====
                new Car { Brand = "Yamaha", Model = "YZF-R1M", Year = 2024, Price = 2_500_000m, LicenseCategory = "A", MaxSpeedKmh = 299, HorsePower = 200, EngineType = "Бензиновый R4 Crossplane", EngineVolume = 1.0, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-98", FuelConsumption = 7.0, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Серебристый", Acceleration0to100 = 3.1, Weight = 202, Country = "Япония", Description = "Yamaha YZF-R1M — карбоновый обтекатель и электронная подвеска Öhlins ERS. 200 л.с. кроссплейн-R4 из MotoGP." },

                // ===== Harley-Davidson =====
                new Car { Brand = "Harley-Davidson", Model = "Road Glide CVO", Year = 2024, Price = 4_500_000m, LicenseCategory = "A", MaxSpeedKmh = 180, HorsePower = 121, EngineType = "Бензиновый V-Twin Milwaukee-Eight", EngineVolume = 2.0, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-95", FuelConsumption = 5.8, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Чёрный", Acceleration0to100 = 4.5, Weight = 408, Country = "США", Description = "Harley-Davidson Road Glide CVO — вершина американского круизинга. Milwaukee-Eight 121 Twin, акустика Rockford Fosgate." },

                // ===== Indian =====
                new Car { Brand = "Indian", Model = "Chieftain Dark Horse", Year = 2024, Price = 3_200_000m, LicenseCategory = "A", MaxSpeedKmh = 170, HorsePower = 116, EngineType = "Бензиновый V-Twin Thunder Stroke", EngineVolume = 1.9, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-95", FuelConsumption = 5.5, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Чёрный", Acceleration0to100 = 4.8, Weight = 370, Country = "США", Description = "Indian Chieftain Dark Horse — премиальный круизер с 7\" тачскрином RIDE COMMAND и Thunder Stroke 116 V-Twin." },

                // ===== Suzuki =====
                new Car { Brand = "Suzuki", Model = "Hayabusa", Year = 2024, Price = 2_100_000m, LicenseCategory = "A", MaxSpeedKmh = 299, HorsePower = 190, EngineType = "Бензиновый R4", EngineVolume = 1.3, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-98", FuelConsumption = 6.5, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Серебристый", Acceleration0to100 = 3.2, Weight = 264, Country = "Япония", Description = "Suzuki Hayabusa — легенда скорости. 190 л.с., аэродинамический дизайн сокола и культовый статус с 1999 года." },

                // ===== Renault =====
                new Car { Brand = "Renault", Model = "Megane RS Trophy", Year = 2024, Price = 3_500_000m, LicenseCategory = "B", MaxSpeedKmh = 260, HorsePower = 300, EngineType = "Бензиновый R4 Turbo", EngineVolume = 1.8, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-95", FuelConsumption = 8.2, Seats = 5, BodyType = "Хэтчбек", DriveType = "Передний", Color = "Жёлтый", Acceleration0to100 = 5.7, Weight = 1407, Country = "Франция", Description = "Renault Megane RS Trophy — 300 л.с. хот-хэтч с шасси Cup и гидравлическими отбойниками. Рекордсмен Нюрбургринга." },

                // ===== Peugeot =====
                new Car { Brand = "Peugeot", Model = "508 PSE", Year = 2024, Price = 4_200_000m, LicenseCategory = "B", MaxSpeedKmh = 250, HorsePower = 360, EngineType = "Гибрид R4 Turbo + 2 электромотора", EngineVolume = 1.6, Transmission = "Автомат 8-ст", FuelType = "Гибрид", FuelConsumption = 2.0, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Серый", Acceleration0to100 = 5.2, Weight = 1860, Country = "Франция", Description = "Peugeot 508 PSE — гибридный спортседан 360 л.с. Peugeot Sport Engineered шасси и i-Cockpit кокпит." },

                // ===== Citroën =====
                new Car { Brand = "Citroën", Model = "C5 X Hybrid", Year = 2024, Price = 3_500_000m, LicenseCategory = "B", MaxSpeedKmh = 233, HorsePower = 225, EngineType = "Гибрид R4 Turbo + электромотор", EngineVolume = 1.6, Transmission = "Автомат 8-ст", FuelType = "Гибрид", FuelConsumption = 1.5, Seats = 5, BodyType = "Седан", DriveType = "Передний", Color = "Белый", Acceleration0to100 = 7.9, Weight = 1740, Country = "Франция", Description = "Citroën C5 X — кросс-седан с подвеской Advanced Comfort. Гибрид 225 л.с. и программа Citroën Advanced Comfort." },

                // ===== LADA =====
                new Car { Brand = "LADA", Model = "Vesta Sport", Year = 2024, Price = 1_500_000m, LicenseCategory = "B", MaxSpeedKmh = 193, HorsePower = 145, EngineType = "Бензиновый R4", EngineVolume = 1.8, Transmission = "Механика 5-ст", FuelType = "Бензин АИ-95", FuelConsumption = 8.5, Seats = 5, BodyType = "Седан", DriveType = "Передний", Color = "Красный", Acceleration0to100 = 9.6, Weight = 1230, Country = "Россия", Description = "LADA Vesta Sport — спортивная версия с 145 л.с. Заниженная подвеска, спортивные сиденья и аэродинамический обвес." },
                new Car { Brand = "LADA", Model = "Niva Travel", Year = 2024, Price = 1_200_000m, LicenseCategory = "B", MaxSpeedKmh = 150, HorsePower = 80, EngineType = "Бензиновый R4", EngineVolume = 1.7, Transmission = "Механика 5-ст", FuelType = "Бензин АИ-92", FuelConsumption = 10.0, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Зелёный", Acceleration0to100 = 19.0, Weight = 1410, Country = "Россия", Description = "LADA Niva Travel — легендарный российский внедорожник. Постоянный полный привод, понижайка и блокировка с 1977 года." },

                // ===== Geely =====
                new Car { Brand = "Geely", Model = "Monjaro 2.0T", Year = 2024, Price = 3_200_000m, LicenseCategory = "B", MaxSpeedKmh = 210, HorsePower = 238, EngineType = "Бензиновый R4 Turbo", EngineVolume = 2.0, Transmission = "Автомат 7-ст", FuelType = "Бензин АИ-95", FuelConsumption = 8.6, Seats = 5, BodyType = "Кроссовер", DriveType = "Полный", Color = "Серый", Acceleration0to100 = 7.5, Weight = 1820, Country = "Китай", Description = "Geely Monjaro — китайский премиум-кроссовер на платформе Volvo CMA. Двигатель Volvo 2.0T и 14.6\" экран." },

                // ===== Chery =====
                new Car { Brand = "Chery", Model = "Tiggo 8 Pro Max", Year = 2024, Price = 3_000_000m, LicenseCategory = "B", MaxSpeedKmh = 200, HorsePower = 197, EngineType = "Бензиновый R4 Turbo", EngineVolume = 1.6, Transmission = "Робот DCT 7-ст", FuelType = "Бензин АИ-92", FuelConsumption = 8.0, Seats = 7, BodyType = "Кроссовер", DriveType = "Передний", Color = "Белый", Acceleration0to100 = 8.5, Weight = 1680, Country = "Китай", Description = "Chery Tiggo 8 Pro Max — 7-местный кроссовер с 24.6\" виртуальной панелью. Sony акустика и Level 2+ автопилот." },

                // ===== HAVAL =====
                new Car { Brand = "HAVAL", Model = "Dargo", Year = 2024, Price = 2_800_000m, LicenseCategory = "B", MaxSpeedKmh = 190, HorsePower = 192, EngineType = "Бензиновый R4 Turbo", EngineVolume = 2.0, Transmission = "Автомат 7-ст", FuelType = "Бензин АИ-92", FuelConsumption = 9.5, Seats = 5, BodyType = "Внедорожник", DriveType = "Полный", Color = "Оранжевый", Acceleration0to100 = 9.8, Weight = 1795, Country = "Китай", Description = "HAVAL Dargo — рамный внедорожник с внешностью пикапа. 9\" тачскрин, камера 360° и понижающая передача." },

                // ===== Li Auto =====
                new Car { Brand = "Li Auto", Model = "L9 Max", Year = 2024, Price = 5_500_000m, LicenseCategory = "B", MaxSpeedKmh = 180, HorsePower = 449, EngineType = "Гибрид R4 Turbo + 2 электромотора", EngineVolume = 1.5, Transmission = "1-ст редуктор", FuelType = "Гибрид", FuelConsumption = 0.8, Seats = 6, BodyType = "Внедорожник", DriveType = "Полный", Color = "Серебристый", Acceleration0to100 = 5.3, Weight = 2550, Country = "Китай", Description = "Li Auto L9 — люкс-SUV с EREV гибридом. 3D ToF сенсоры, 15.7\" задний экран для пассажиров и 1315 км запас хода." },

                // ===== BYD =====
                new Car { Brand = "BYD", Model = "Seal Performance", Year = 2024, Price = 4_200_000m, LicenseCategory = "B", MaxSpeedKmh = 180, HorsePower = 530, EngineType = "Электрический (2 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Синий", Acceleration0to100 = 3.8, Weight = 2150, Country = "Китай", Description = "BYD Seal — электроседан на платформе e-Platform 3.0. Blade Battery, Cell-to-Body и 700 км запас хода." },
                new Car { Brand = "BYD", Model = "Tang EV", Year = 2024, Price = 5_000_000m, LicenseCategory = "B", MaxSpeedKmh = 180, HorsePower = 517, EngineType = "Электрический (2 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 7, BodyType = "Внедорожник", DriveType = "Полный", Color = "Красный", Acceleration0to100 = 4.4, Weight = 2560, Country = "Китай", Description = "BYD Tang EV — электрический 7-местный SUV. Blade Battery, 15.6\" вращающийся экран и DiPilot автопилот." },

                // ===== NIO =====
                new Car { Brand = "NIO", Model = "ET7", Year = 2024, Price = 6_500_000m, LicenseCategory = "B", MaxSpeedKmh = 200, HorsePower = 653, EngineType = "Электрический (2 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Белый", Acceleration0to100 = 3.8, Weight = 2379, Country = "Китай", Description = "NIO ET7 — флагман с LiDAR Aquila и сменными батареями BaaS. 150 kWh батарея = 1000+ км запас хода." },

                // ===== Rivian =====
                new Car { Brand = "Rivian", Model = "R1T Adventure", Year = 2024, Price = 8_000_000m, LicenseCategory = "B", MaxSpeedKmh = 201, HorsePower = 835, EngineType = "Электрический (4 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Пикап", DriveType = "Полный", Color = "Зелёный", Acceleration0to100 = 3.0, Weight = 3075, Country = "США", Description = "Rivian R1T — электрический пикап с 4 моторами. 835 л.с., тоннель для снаряжения и 1 м преодоление водных преград." },

                // ===== Lucid =====
                new Car { Brand = "Lucid", Model = "Air Sapphire", Year = 2024, Price = 18_000_000m, LicenseCategory = "B", MaxSpeedKmh = 330, HorsePower = 1234, EngineType = "Электрический (3 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 5, BodyType = "Седан", DriveType = "Полный", Color = "Синий", Acceleration0to100 = 1.9, Weight = 2360, Country = "США", Description = "Lucid Air Sapphire — 1234 л.с., 0-100 за 1.89 сек. Самый быстрый серийный седан в мире. Запас хода 687 км." },

                // ===== Rimac =====
                new Car { Brand = "Rimac", Model = "Nevera", Year = 2024, Price = 200_000_000m, LicenseCategory = "B", MaxSpeedKmh = 412, HorsePower = 1914, EngineType = "Электрический (4 мотора)", EngineVolume = 0.0, Transmission = "1-ст редуктор", FuelType = "Электро", FuelConsumption = 0.0, Seats = 2, BodyType = "Гиперкар", DriveType = "Полный", Color = "Серебристый", Acceleration0to100 = 1.81, Weight = 2150, Country = "Хорватия", Description = "Rimac Nevera — электрический гиперкар с 1914 л.с. и 2360 Нм. Мировой рекорд 0-100 за 1.81 секунды." },

                // ===== Lotus =====
                new Car { Brand = "Lotus", Model = "Emira V6", Year = 2024, Price = 12_000_000m, LicenseCategory = "B", MaxSpeedKmh = 290, HorsePower = 400, EngineType = "Бензиновый V6 Supercharged", EngineVolume = 3.5, Transmission = "Автомат 6-ст", FuelType = "Бензин АИ-98", FuelConsumption = 10.2, Seats = 2, BodyType = "Спорткар", DriveType = "Задний", Color = "Жёлтый", Acceleration0to100 = 4.2, Weight = 1405, Country = "Великобритания", Description = "Lotus Emira — последний спорткар Lotus с ДВС. Toyota V6 400 л.с. и философия lightweight от Колина Чепмена." },

                // ===== Porsche Motorcycle =====
                new Car { Brand = "Honda", Model = "CBR1000RR-R Fireblade SP", Year = 2024, Price = 2_800_000m, LicenseCategory = "A", MaxSpeedKmh = 299, HorsePower = 217, EngineType = "Бензиновый R4", EngineVolume = 1.0, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-98", FuelConsumption = 6.5, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Красный", Acceleration0to100 = 2.9, Weight = 201, Country = "Япония", Description = "Honda CBR1000RR-R SP — 217 л.с. с технологиями RC213V MotoGP. Öhlins NPX подвеска и Brembo Stylema тормоза." },

                // ===== Aprilia =====
                new Car { Brand = "Aprilia", Model = "RSV4 Factory", Year = 2024, Price = 2_600_000m, LicenseCategory = "A", MaxSpeedKmh = 299, HorsePower = 217, EngineType = "Бензиновый V4", EngineVolume = 1.1, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-98", FuelConsumption = 7.0, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Чёрный", Acceleration0to100 = 3.0, Weight = 202, Country = "Италия", Description = "Aprilia RSV4 Factory — итальянский суперспорт с 65° V4 217 л.с. APRC электроника и Öhlins Smart EC 2.0 подвеска." },

                // ===== KTM =====
                new Car { Brand = "KTM", Model = "1290 Super Duke R EVO", Year = 2024, Price = 2_300_000m, LicenseCategory = "A", MaxSpeedKmh = 270, HorsePower = 180, EngineType = "Бензиновый V-Twin LC8", EngineVolume = 1.3, Transmission = "Механика 6-ст", FuelType = "Бензин АИ-98", FuelConsumption = 6.0, Seats = 2, BodyType = "Мотоцикл", DriveType = "Задний", Color = "Оранжевый", Acceleration0to100 = 3.2, Weight = 189, Country = "Австрия", Description = "KTM 1290 Super Duke R — The Beast. 180 л.с. V-Twin, WP Semi-Active подвеска и самый агрессивный нейкед." },
            };

            context.Cars.AddRange(cars);
            context.SaveChanges();
        }
    }
}
